<?php

namespace Mike\CharacterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CharacterAttributesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharacterAttributesRepository extends EntityRepository
{
}
