<?php

namespace Mike\CharacterBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CharactersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CharactersRepository extends EntityRepository
{
}
